language: generic
jobs:
  include:
  - stage: unit tests
    script:
    - ./a.sh
  - stage: staging
    if: branch = staging or branch = prod
    script:
    - ./b.sh
  - stage: prod
    if: branch = prod
    script:
    - ./c.sh